apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: external-secrets
  namespace: kubocd-system
spec:
  description: "External Secrets Operator for syncing secrets from external APIs"
  package:
    repository: quay.io/okdp/packages-dev/external-secrets
    tag: 0.1.0
    interval: 30m
    timeout: 10m
  parameters:
    installCRDs: true
    webhook:
      enabled: true
    certController:
      enabled: true
  targetNamespace: external-secrets
  createNamespace: true
